<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Programme', 'doctrine');

/**
 * BaseProgramme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $fk_talks
 * @property string $room
 * @property text $day
 * @property time $timestart
 * @property time $timeend
 * @property text $type
 * 
 * @method integer   getId()        Returns the current record's "id" value
 * @method integer   getFkTalks()   Returns the current record's "fk_talks" value
 * @method string    getRoom()      Returns the current record's "room" value
 * @method text      getDay()       Returns the current record's "day" value
 * @method time      getTimestart() Returns the current record's "timestart" value
 * @method time      getTimeend()   Returns the current record's "timeend" value
 * @method text      getType()      Returns the current record's "type" value
 * @method Programme setId()        Sets the current record's "id" value
 * @method Programme setFkTalks()   Sets the current record's "fk_talks" value
 * @method Programme setRoom()      Sets the current record's "room" value
 * @method Programme setDay()       Sets the current record's "day" value
 * @method Programme setTimestart() Sets the current record's "timestart" value
 * @method Programme setTimeend()   Sets the current record's "timeend" value
 * @method Programme setType()      Sets the current record's "type" value
 * 
 * @package    frontendconference
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProgramme extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('programme');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fk_talks', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('room', 'string', 32, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 32,
             ));
        $this->hasColumn('day', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('timestart', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('timeend', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('type', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'Talk',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}