<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Attendees', 'doctrine');

/**
 * BaseAttendees
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $email
 * @property timestamp $entrytime
 * 
 * @method integer   getId()        Returns the current record's "id" value
 * @method string    getEmail()     Returns the current record's "email" value
 * @method timestamp getEntrytime() Returns the current record's "entrytime" value
 * @method Attendees setId()        Sets the current record's "id" value
 * @method Attendees setEmail()     Sets the current record's "email" value
 * @method Attendees setEntrytime() Sets the current record's "entrytime" value
 * 
 * @package    frontendconference
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAttendees extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('attendees');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('entrytime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}