<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/15 22:37:38

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=fec',
  'username' => 'fec',
  'password' => '5gz4HfUqQK',
  'name' => 'doctrine',
)),);
