<?php

/**
 * ProgrammeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProgrammeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProgrammeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Programme');
    }
}