<?php

/**
 * SpeakersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpeakersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SpeakersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Speakers');
    }
}