<?php

/**
 * TalksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TalksTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TalksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Talks');
    }
}