<?php

/**
 * Talks
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    frontendconference
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Talks extends BaseTalks
{
  public function setUp()
  {
      parent::setUp();
      $this->hasOne('Programme', array(
              'local' => 'id',
              'foreign' => 'fk_talks'
          )
      );
      
  }
}
