# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:         Frontend Conference Zurich - September 9th & 10th 2011
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [reset.css, main.css]

  javascripts:    [css3-mediaqueries.js]

  has_layout:     true
  layout:         layout
